version: 1.{build}

platform:
    - x64
    - Win32

build_script:
    - .\bundle.cmd

artifacts:
    - path: _build\Sysmo-NMS-*.exe

deploy:
    release: CURRENT
    description: 'Sysmo NMS release (Sysmo-Core and Sysmo-Operator bundle)'
    provider: GitHub
    auth_token:
        secure: JbU57GgB5EBgwKdw4kTc2LTimc85On9dVaiCAbnqIPRbQxEs6KFEBOHxh8eFuqqD
    artifact: /Sysmo-NMS-.*\.exe/
    force_update: true
    draft: true
    prerelease: false
    on:
        branch: master
        appveyor_repo_tag: false


cache:
  - C:\Users\appveyor\SYSMO_NMS_RESSOURCES\

